---
## ---------------
## ビルド機能の有効化
## ---------------
enable:
  - js
  - css
  - html
  - copy
## ---------------
## HTMLビルド機能の設定
## ---------------
html:
  ignore:
    dirNames:
      - element
      - layout
  siteUrl: 'https://tool-s.xyz/'

